CAST-36035 update ACLs to apply to default vrf
Cray-HPE/canu pull request #471
Opened 2024-06-28 18:55 UTC by lukebates123

### Summary and Scope

 update ACLs to apply to default vrf

- [ ] I have added new tests to cover the new code
- [ ] If adding a new file, I have updated `pyinstaller.py`
- [ ] I have added entries in `CHANGELOG.md` for the changes in this PR

### Issues and Related PRs

### Testing

Tested on Surtur.

2024-08-12 16:07 UTC, rustydb requested changes

2024-08-12 16:07 UTC, rustydb commented on network_modeling/configs/templates/1.5/aruba/common/acl.j2
> +apply access-list ip mgmt control-plane vrf CSM
Should this be?
```suggestion
apply access-list ip mgmt control-plane vrf {{ variables.VRF }}
```

2024-08-12 16:07 UTC, rustydb commented on network_modeling/configs/templates/1.6/aruba/common/acl.j2
> +apply access-list ip mgmt control-plane vrf CSM
Same comment:
```suggestion
apply access-list ip mgmt control-plane vrf {{ variables.VRF }}
```

2024-08-12 16:07 UTC, rustydb commented on network_modeling/configs/templates/1.5/aruba/common/acl.j2
> +apply access-list ip mgmt control-plane vrf CSM
Also should line 276(ish) in `canu/generate/switch/config/config.py` have its default capitalized?

2024-11-18 18:30 UTC, rustydb approved these changes

2025-01-08 16:48 UTC, spillerc-hpe approved these changes

2025-01-08 16:49 UTC, merged